### ISSUE TITLE
Add instance identifier for online multiplayer

### ISSUE THREAD

**Issue by lheinke** [matjlars/godot-multiplayer-input#11]
I am working on a multiplayer versus game where I want to implement multiplayer both locally as well as over peer-to-peer networking. Therefore, I was wondering if it would be possible to add some way of specifying an additional identifier to discriminate between inputs from devices from different instances. I understand that this is probably out of scope for this small add-on, but just wanted to know if you would be interested in adding this.

**Comment by matjlars** [comment]
How would it work? My first reaction says maybe that would be a good piece of data to store in your PlayerManager.  There is almost always a need to store some meta data for each player and which network id they are could be stored there. See my example player manager class for what I mean.  That said, I'm not sure how you are planning on using that. Typically, the controller states are not synced over the network, but rather the character positions, rotations, health values, etc. I think because of that, this does fall out of scope for this addon.

I'm going to close the issue but feel free to keep discussing here or re-open if you want me to reconsider.
