### ISSUE TITLE
I'm couldn't get the setup to work, i really need some help.

### ISSUE THREAD

**Issue by GM637** [matjlars/godot-multiplayer-input#14]
Im trying to make a simple party game where player 1 can use keyboard or a gamepad, while the rest of players can use any extra gamepads connected. no luck so far, the assert error #8  keep popping up, i have no idea what i shouldn't be doing, aside from my game simply using the ui_actions to play (the control scheme is just a directional input and a button, so i just the ui_actions as input rather than creating any extra input actions) im still very bummed and is absolutely clueless on how this should actually work, please help, if you need a specific screenshot just tell me, but right now, idk what should i share as all the use in my project so far is very simple and nothing that can potentially lead to these issues.

but i can explain the player system, all players are available on scene rather than creating new players when they join, theyre all hidden except player 1, and when other players press an input, it enables other players to use their respective player object to play

**Comment by matjlars** [comment]
Hi!  Try creating new actions for the stuff you want each player to do
instead of using the ui actions. explanation: sometimes in multiplayer
games you want one player to control a menu, so the ui actions are kind of
separated out from your normally defined actions. Check out the doc
comments on MultiplayerInput.set_ui_action_device for more details. Let me
know if that works for you!

**Comment by matjlars** [comment]
I'm going to close this issue but feel free to re-open it or create a new issue! I don't mind helping at all. Cheers.
