### ISSUE TITLE
Seems is_action_released is missing & handling keyboard and gamepad 0 as player 1

### ISSUE THREAD

**Issue by jordanmichaelrushing** [matjlars/godot-multiplayer-input#7]
Running into two problems currently.

1: I'm not seeing `is_action_released` declared anywhere in the code. Is this missing on purpose? 

2: I want to be able to make player 1 be able to use the keyboard or the first gamepad. Currently I'm using this library in conjunction with checking -1 & 0 as the same vs all other device IDs. Is there anything built in to be able to handle keyboard and gamepad 0 as the same player?

**Comment by matjlars** [comment]
Hello! is_action_released does not exist. You either want is_action_just_released or !is_action_pressed

this addon lets you keep track of your devices any way you want. it's hard for me to help you let player 1 use two devices without seeing your code but it is certainly possible. just make two calls to the MultiplayerInput functions for player 1, with device -1 and 0. You may want to consider something other than hardcoding 0 because if you have a bunch of controllers, the one that is considered device 0 will be arbitrary and may not be what the player intends.

**Comment by jordanmichaelrushing** [comment]
> Hello! is_action_released does not exist. You either want is_action_just_released or !is_action_pressed

Thanks! Yeah I just saw the is_action_released is only available on InputEvent and not Input

**Comment by jordanmichaelrushing** [comment]
> if you have a bunch of controllers, the one that is considered device 0 will be arbitrary and may not be what the player intends.
Yeah that's a really good point if player 1 is keyboard and player 2 is the only other gamepad, being device 0...

Thanks a bunch this was really helpful

**Comment by matjlars** [comment]
Your're welcome! Glad I could help!
